/**
 * BaseProject API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Bookmark { 
    id: number | null;
    name: string | null;
    link: string | null;
    createdAt: string;
    createdBy: string | null;
    modifiedAt: string | null;
    modifiedBy: string | null;
    users: Array<User> | null;
}

