/**
 * BaseProject API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Car { 
    id: number | null;
    brandName: string | null;
    modelName: string | null;
    power: number;
    vmax: number;
}

