/**
 * BaseProject API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Bookmark } from './bookmark';


export interface User { 
    id: number | null;
    firstName: string | null;
    lastName: string | null;
    eMail: string | null;
    password: string | null;
    bookmarks: Array<Bookmark> | null;
}

