# https://docs.dapr.io/reference/components-reference/supported-secret-stores/file-secret-store/

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore-local
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "./secrets.json"
    - name: nestedSeparator
      value: ":"
    - name: multiValued
      value: "false"